services:
  fileviewer:
    build: .
    image: registry.seadee.com.cn:5000/fileviewer:latest
    container_name: fileviewer
    volumes:
      - ./:/workspace
    working_dir: /workspace
    environment:
      - WATCH_DIR=/workspace
    restart: unless-stopped
    tty: true
