services:
  fileviewer:
    build: .
    image: registry.seadee.com.cn:5000/fileviewer:latest
    container_name: fileviewer
    volumes:
      - ./:/workspace
    working_dir: /workspace
    environment:
      - WATCH_DIR=/workspace
      - SITE_NAME=${SITE_NAME:-文件浏览器}
    restart: unless-stopped
    tty: true
    networks:
      - virtualink

networks:
  virtualink:
    external: true